import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Denim Jacket',
    description: 'A timeless denim jacket made from 100% organic cotton. Perfect for layering in any season.',
    price: 7500,
    category: 'Jackets',
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    keywords: ['denim', 'casual', 'outerwear', 'classic'],
    rating: 4.5,
    reviewCount: 120,
    reviews: [
      { id: 1, author: 'Aisha', rating: 5, text: 'Great quality and fit!', date: '2023-05-10' },
      { id: 2, author: 'Brian', rating: 4, text: 'Very versatile jacket.', date: '2023-05-12' },
    ],
  },
  {
    id: '2',
    name: 'Linen Blend Shirt',
    description: 'A breathable and stylish linen blend shirt, ideal for warm weather. Available in multiple colors.',
    price: 4200,
    category: 'Shirts',
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    keywords: ['linen', 'summer', 'smart casual', 'breathable'],
    rating: 4.7,
    reviewCount: 95,
    reviews: [
      { id: 1, author: 'Chloe', rating: 5, text: 'So comfortable and looks sharp.', date: '2023-06-20' },
    ],
  },
  {
    id: '3',
    name: 'Tailored Chino Trousers',
    description: 'Modern slim-fit chinos that bridge the gap between casual and formal. Made with a hint of stretch for comfort.',
    price: 5500,
    category: 'Trousers',
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    keywords: ['chinos', 'smart casual', 'workwear', 'slim fit'],
    rating: 4.6,
    reviewCount: 150,
    reviews: [],
  },
  {
    id: '4',
    name: 'Floral Maxi Dress',
    description: 'An elegant floral maxi dress with a flowing silhouette. Perfect for weddings, parties, or a summer day out.',
    price: 9800,
    category: 'Dresses',
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    keywords: ['floral', 'maxi dress', 'occasionwear', 'elegant'],
    rating: 4.9,
    reviewCount: 78,
    reviews: [],
  },
  {
    id: '5',
    name: 'Merino Wool Sweater',
    description: 'A soft and luxurious sweater crafted from 100% Merino wool. Lightweight yet incredibly warm.',
    price: 8900,
    category: 'Knitwear',
    images: ['https://placehold.co/600x800.png'],
    keywords: ['wool', 'sweater', 'luxury', 'winter'],
    rating: 4.8,
    reviewCount: 110,
    reviews: [],
  },
  {
    id: '6',
    name: 'Leather Ankle Boots',
    description: 'Handcrafted leather boots with a durable sole and comfortable insole. A versatile addition to any wardrobe.',
    price: 15000,
    category: 'Shoes',
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    keywords: ['leather', 'boots', 'footwear', 'handmade'],
    rating: 4.7,
    reviewCount: 88,
    reviews: [],
  },
  {
    id: '7',
    name: 'Graphic Print T-Shirt',
    description: 'A soft cotton t-shirt featuring a unique, artist-designed graphic print. Express your style.',
    price: 2500,
    category: 'T-Shirts',
    images: ['https://placehold.co/600x800.png'],
    keywords: ['t-shirt', 'graphic tee', 'casual', 'streetwear'],
    rating: 4.4,
    reviewCount: 210,
    reviews: [],
  },
  {
    id: '8',
    name: 'Pleated A-Line Skirt',
    description: 'A chic and versatile pleated skirt with a flattering A-line cut. Easily dressed up or down.',
    price: 6200,
    category: 'Skirts',
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    keywords: ['skirt', 'pleated', 'A-line', 'chic'],
    rating: 4.6,
    reviewCount: 65,
    reviews: [],
  },
];
